/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codematch;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nonpr
 */
public class MainFrame extends javax.swing.JFrame {
    public static boolean isItems = true;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void clearText(){
        first_textField.setText("");
        second_textField.setText("");
        third_textField.setText("");
        first_comboBox.setSelectedIndex(-1);
    }
    
    private boolean isEmpty(){
        if(isItems){
            if(first_textField.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Product Name is required!", "Warning", 2);
                return true;
            }
            if((second_textField.getText().equals("")) ){
                JOptionPane.showMessageDialog(this, "Product Price is required!", "Warning", 2);
                return true;
         }
            if(Double.parseDouble(second_textField.getText()) <= 0){
                JOptionPane.showMessageDialog(this, "Plase, increase the product price", "Warning", 2);
                return true;
            }
            if((third_textField.getText().equals("")) ){
                JOptionPane.showMessageDialog(this, "Product Quantity is required!", "Warning", 2);
                return true;
            }
            if(Integer.parseInt(third_textField.getText()) <= 0){
                JOptionPane.showMessageDialog(this, "Plase, increase the product quantity", "Warning", 2);
                return true;
            }
            if(first_comboBox.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(this, "Plase, select the category", "Warning", 2);
                return true;
            }
        }
        else if(!isItems){
            if((first_textField.getText().equals("")) ){
                JOptionPane.showMessageDialog(this, "Discount is required!", "Warning", 2);
                return true;
            }
            if(Integer.parseInt(first_textField.getText()) <= 0){
                JOptionPane.showMessageDialog(this, "Plase, increase the product quantity", "Warning", 2);
                return true;
            }
            if((second_textField.getText().equals("")) ){
                JOptionPane.showMessageDialog(this, "Min is required!", "Warning", 2);
                return true;
            }
            if((Integer.parseInt(second_textField.getText()) < 0) || (Integer.parseInt(second_textField.getText()) > Integer.parseInt(third_textField.getText()))){
                
                JOptionPane.showMessageDialog(this, "Min is incorrect!", "Warning", 2);
                return true;
            }
            if((third_textField.getText().equals("")) ){
                JOptionPane.showMessageDialog(this, "Max is required!", "Warning", 2);
                return true;
            }
            if((Integer.parseInt(third_textField.getText()) < 0) || (Integer.parseInt(third_textField.getText()) < Integer.parseInt(second_textField.getText()))){
                JOptionPane.showMessageDialog(this, "Max is incorrect!", "Warning", 2);
                return true;
            }
            if(first_comboBox.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(this, "Plase, select the category", "Warning", 2);
                return true;
            }
            if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected()){
                JOptionPane.showMessageDialog(this, "Plase, select the type", "Warning", 2);
                return true;
            }
        }
        return false;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        first_label = new javax.swing.JLabel();
        third_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coupon_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        first_textField = new javax.swing.JTextField();
        second_textField = new javax.swing.JTextField();
        third_textField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        second_label = new javax.swing.JLabel();
        fourth_label = new javax.swing.JLabel();
        first_comboBox = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        total_label = new javax.swing.JLabel();
        total_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeMatch");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        first_label.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        first_label.setText("Product Name");

        third_label.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        third_label.setText("Quantity");

        coupon_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Discount", "Type", "Category", "Min Discount", "Max Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coupon_table.getTableHeader().setReorderingAllowed(false);
        coupon_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coupon_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(coupon_table);
        if (coupon_table.getColumnModel().getColumnCount() > 0) {
            coupon_table.getColumnModel().getColumn(0).setResizable(false);
            coupon_table.getColumnModel().getColumn(1).setResizable(false);
            coupon_table.getColumnModel().getColumn(2).setResizable(false);
            coupon_table.getColumnModel().getColumn(3).setResizable(false);
            coupon_table.getColumnModel().getColumn(4).setResizable(false);
        }

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_table.getTableHeader().setReorderingAllowed(false);
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                product_tableMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                product_tableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(product_table);
        if (product_table.getColumnModel().getColumnCount() > 0) {
            product_table.getColumnModel().getColumn(0).setResizable(false);
            product_table.getColumnModel().getColumn(1).setResizable(false);
            product_table.getColumnModel().getColumn(2).setResizable(false);
            product_table.getColumnModel().getColumn(3).setResizable(false);
            product_table.getColumnModel().getColumn(4).setResizable(false);
        }

        first_textField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        first_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_textFieldActionPerformed(evt);
            }
        });

        second_textField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        second_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_textFieldActionPerformed(evt);
            }
        });
        second_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                second_textFieldKeyTyped(evt);
            }
        });

        third_textField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        third_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                third_textFieldActionPerformed(evt);
            }
        });
        third_textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                third_textFieldKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("SWITCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        delete_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setText("MATCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        second_label.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        second_label.setText("Price");

        fourth_label.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fourth_label.setText("Category");

        first_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mall", "Khum", "Normal" }));
        first_comboBox.setSelectedIndex(-1);
        first_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_comboBoxActionPerformed(evt);
            }
        });

        shopType.add(jRadioButton1);
        jRadioButton1.setText("Shopee");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        shopType.add(jRadioButton2);
        jRadioButton2.setText("Shop");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        total_label.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        total_label.setText("Total :");

        total_label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_label1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fourth_label)
                            .addComponent(first_label)
                            .addComponent(second_label)
                            .addComponent(third_label)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(first_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(second_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(third_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(first_comboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(total_label)
                        .addGap(18, 18, 18)
                        .addComponent(total_label1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(first_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(first_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(second_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(second_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(third_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(third_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourth_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(first_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_label)
                            .addComponent(total_label1))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(isItems){
            first_label.setText("Discount");
            second_label.setText("Min Discount");
            third_label.setText("Max Discount");
            
            
            String data[] = {"Free Shipping","Percentage","Absolute"};
            DefaultComboBoxModel mod = new DefaultComboBoxModel(data);
            first_comboBox.setModel(mod);
            first_comboBox.setSelectedIndex(-1);
            
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            
            clearText();
            shopType.clearSelection();
            
            isItems = false;
        }
        else{
            first_label.setText("Product Name");
            second_label.setText("Price");
            third_label.setText("Quantity");
            
            
            String data[] = {"Mall", "Khum", "Normal"};
            DefaultComboBoxModel mod = new DefaultComboBoxModel(data);
            first_comboBox.setModel(mod);
            first_comboBox.setSelectedIndex(-1);
            
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            
            clearText();
            shopType.clearSelection();
            
            isItems = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (isItems){
            if(!isEmpty()){
                String name = first_textField.getText();
                String category = first_comboBox.getSelectedItem().toString();
                double price = Double.parseDouble(second_textField.getText());
                int quantity = Integer.parseInt(third_textField.getText());
                String total = String.format("%.2f",(price * (double)quantity));
            
                String data[] = {name,category,second_textField.getText(),third_textField.getText(),total};
                DefaultTableModel tblItemsModel = (DefaultTableModel)product_table.getModel();
                tblItemsModel.addRow(data);
                
                double totalPrice = Double.parseDouble(total_label1.getText());
                totalPrice += Double.parseDouble(total);
                total_label1.setText(String.format("%.2f",totalPrice));
            
                clearText();
            }
        }
        else{
            if(!isEmpty()){
                String category = first_comboBox.getSelectedItem().toString();
                String type = "";
                if (jRadioButton1.isSelected()){
                    type = "Shopee";
                }
                else if (jRadioButton2.isSelected()){
                    type = "Shop";
                }
                String data[] = {first_textField.getText(),type,category,second_textField.getText(),third_textField.getText()};
                DefaultTableModel tblCousModel = (DefaultTableModel)coupon_table.getModel();
                tblCousModel.addRow(data);
            
                clearText();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)product_table.getModel();
        DefaultTableModel tblCouModel = (DefaultTableModel)coupon_table.getModel();
        if(product_table.getRowCount()==0 && coupon_table.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table is empty", "Warning", 2);
        }
        else if(product_table.getSelectedRowCount()<=0 && coupon_table.getSelectedRowCount()<=0){
            JOptionPane.showMessageDialog(this, "Please select row to delete", "Warning", 2);
        }
        else{
       
            if(product_table.getSelectedRow() != 1 || product_table.getSelectedRow() > 0){
                int cnt_items = product_table.getSelectedRow();
                while (cnt_items != -1){
                    int modelCnt = product_table.convertRowIndexToModel(cnt_items);
                    String total = tblModel.getValueAt(cnt_items,4).toString();
                    System.out.println(total);
                    tblModel.removeRow(modelCnt);
                    cnt_items = product_table.getSelectedRow();
                    
                    double totalPrice = Double.parseDouble(total_label1.getText());                   
                    totalPrice -= Double.parseDouble(total);
                    total_label1.setText(String.format("%.2f",totalPrice));
                }
            }
            if (coupon_table.getSelectedRow() != 1 || coupon_table.getSelectedRow() > 0){
                int cnt_cou = coupon_table.getSelectedRow();
                while (cnt_cou != -1){
                    int modelCnt = coupon_table.convertRowIndexToModel(cnt_cou);
                    tblCouModel.removeRow(modelCnt);
                    cnt_cou = coupon_table.getSelectedRow();
                }
            }
        }
            
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void first_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_textFieldActionPerformed

    private void second_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_second_textFieldActionPerformed

    private void third_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_third_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_third_textFieldActionPerformed

    private void first_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_comboBoxActionPerformed

    private void third_textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_third_textFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){evt.consume();}
    }//GEN-LAST:event_third_textFieldKeyTyped

    private void second_textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_second_textFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){evt.consume();}
    }//GEN-LAST:event_second_textFieldKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() > 1)
            product_table.clearSelection();
        
        
    }//GEN-LAST:event_product_tableMouseClicked

    private void product_tableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_product_tableMouseExited

    private void product_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_product_tableMouseReleased

    private void coupon_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coupon_tableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() > 1)
            product_table.clearSelection();
    }//GEN-LAST:event_coupon_tableMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable coupon_table;
    private javax.swing.JButton delete_btn;
    private javax.swing.JComboBox<String> first_comboBox;
    private javax.swing.JLabel first_label;
    private javax.swing.JTextField first_textField;
    private javax.swing.JLabel fourth_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable product_table;
    private javax.swing.JLabel second_label;
    private javax.swing.JTextField second_textField;
    private javax.swing.ButtonGroup shopType;
    private javax.swing.JLabel third_label;
    private javax.swing.JTextField third_textField;
    private javax.swing.JLabel total_label;
    private javax.swing.JLabel total_label1;
    // End of variables declaration//GEN-END:variables
}
